### ISSUE TITLE
OpenROAD

### ISSUE THREAD

**Issue by amithmath** [black-parrot/black-parrot-sim#15]
Is there any repo for black-parrot using OpenROAD CAD tool?

**Comment by dpetrisko** [comment]
Hi, parts of BlackParrot are being used in the openroad repo as a test case. However, there is currently no repo for a full BlackParror synthesis run. 

This is due to a lack of support for SystemVerilog in yosys. There's an ongoing collaboration to improve compatibility in the tools and we should be able to show something soon!

**Comment by amithmath** [comment]
OK thanks
