### ISSUE TITLE
BlackParrot 16 cores

### ISSUE THREAD

**Issue by amithmath** [black-parrot/black-parrot-sim#17]
I am curious to know why BlackParrot scale up to 16 cores? Why not 32 cores, 64 cores, etc.? Is there any limitations with respect to linux OS?  Or any other issues?

**Comment by dpetrisko** [comment]
It's a good question. There is no physical design restriction on number of cores since the interconnect fabric is based on a scalable wormhole mesh. 16 cores was simply our original target for architectural tuning. 

Once you go past 16 cores, traditional coherence protocols start to become more of an performance overhead and schemes such as hierarchical snooping and partial directories become more attractive. Because we haven't explored these techniques, we haven't tried to scale further. 

However, give it a try! Would love to see a 64 core BP chip

**Comment by amithmath** [comment]
OK got it thanks.
